# Generated by Django 3.1.3 on 2023-04-07 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_auto_20230407_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='qvalue',
            field=models.IntegerField(),
        ),
    ]
