# Generated by Django 3.1.3 on 2023-04-07 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0003_auto_20230407_0626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='questions',
        ),
        migrations.AddField(
            model_name='choice',
            name='question_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='onlinecourse.question'),
        ),
    ]
