# Generated by Django 3.1.3 on 2023-04-09 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0004_auto_20230407_0721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='question_id',
            new_name='questionid',
        ),
    ]
